2024-08-18 19:01:27.098 - componentLogger - Launcher.startup - ERROR - 组件注册运行发生异常:<AioRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = ""
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-08-18T11:01:27.0879676+00:00", grpc_status:2, grpc_message:""}"
>
Traceback (most recent call last):
  File "C:\Users\st1\Desktop\2024bci_group3\2024bci_group2\2024bci_group2\Stimulator\ApplicationFramework\launcher\Launcher.py", line 86, in startup
    await self.__component_framework.register_component(component_model)
  File "C:\Users\st1\Desktop\2024bci_group3\2024bci_group2\2024bci_group2\Stimulator\ApplicationFramework\facade\ComponentFrameworkImplement.py", line 93, in register_component
    registered_component: ComponentModel_CCM = await self.__component_manager.component_register(
  File "C:\Users\st1\Desktop\2024bci_group3\2024bci_group2\2024bci_group2\Stimulator\componentframework\control\ComponentManagerInterfaceImpl.py", line 44, in component_register
    self.component_register_result = await self.__component_forwarder.component_register(component_model)
  File "C:\Users\st1\Desktop\2024bci_group3\2024bci_group2\2024bci_group2\Stimulator\componentframework\service\ComponentManagerService.py", line 48, in component_register
    self.component_register_result = await self.__component_forwarder.component_register(component_model)
  File "C:\Users\st1\Desktop\2024bci_group3\2024bci_group2\2024bci_group2\Stimulator\componentframework\facadeImpl\ComponentManagerFacadeImpl.py", line 57, in component_register
    response = await self.stub.RegisterComponent(request)
  File "C:\Users\st1\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\aio\_call.py", line 327, in __await__
    raise _create_rpc_error(
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = ""
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-08-18T11:01:27.0879676+00:00", grpc_status:2, grpc_message:""}"
>
2024-08-18 19:01:27.117 - componentLogger - Launcher.shutdown - ERROR - 组件注销发生异常:<AioRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = ""
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-08-18T11:01:27.1161528+00:00", grpc_status:2, grpc_message:""}"
>
Traceback (most recent call last):
  File "C:\Users\st1\Desktop\2024bci_group3\2024bci_group2\2024bci_group2\Stimulator\ApplicationFramework\launcher\Launcher.py", line 97, in shutdown
    await self.__component_framework.unregister_component()
  File "C:\Users\st1\Desktop\2024bci_group3\2024bci_group2\2024bci_group2\Stimulator\ApplicationFramework\facade\ComponentFrameworkImplement.py", line 105, in unregister_component
    await self.__component_manager.unregister_component()
  File "C:\Users\st1\Desktop\2024bci_group3\2024bci_group2\2024bci_group2\Stimulator\componentframework\control\ComponentManagerInterfaceImpl.py", line 129, in unregister_component
    self.unregister_component_result = await self.__component_forwarder.unregister_component()
  File "C:\Users\st1\Desktop\2024bci_group3\2024bci_group2\2024bci_group2\Stimulator\componentframework\service\ComponentManagerService.py", line 133, in unregister_component
    self.unregister_component_result = await self.__component_forwarder.unregister_component()
  File "C:\Users\st1\Desktop\2024bci_group3\2024bci_group2\2024bci_group2\Stimulator\componentframework\facadeImpl\ComponentManagerFacadeImpl.py", line 145, in unregister_component
    response = await self.stub.UnregisterComponent(request)
  File "C:\Users\st1\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\aio\_call.py", line 327, in __await__
    raise _create_rpc_error(
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = ""
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-08-18T11:01:27.1161528+00:00", grpc_status:2, grpc_message:""}"
>
